### PR TITLE
Add test consumer for study

### PR DESCRIPTION
**Pull request by catdolls**

### CODE REVIEW

**Comment by mefellows** [comment]
Did you mean to raise the PR to this repo?

**Comment by catdolls** [comment]
> Did you mean to raise the PR to this repo?

Yes, just want to share code for my friend. Do you know how can I create PR for only this fork.

**Comment by mefellows** [comment]
When you open the pull request, by default the base will be for the forked repo (i.e. this one). Just select the correct base to your repository and it should be good to go.

If you just wanted to share your changes with a friend, they are already visible on your repo branch here: https://github.com/catdolls/pact-workshop-js/tree/test-consumer

**Comment by catdolls** [comment]
Thank you for your suggestion.

**Pull request closed without merging**
